### ISSUE TITLE
Snuba subscriptions consumer (events/transactions) OFFSET_OUT_OF_RANGE

### ISSUE THREAD

**Issue by Antiarchitect** [getsentry/self-hosted#1199]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.8.0

### Steps to Reproduce

1. Make Kafka lose offsets

### Expected Result

All services are up eventually correcting OFFSET_OUT_OF_RANGE errors by `autoOffsetReset: earliest` is set by default in Sentry chart.

### Actual Result

All services except   subscriptionConsumerEvents and  subscriptionConsumerTransactions are up despite of it seems like they are also configured properly:

```
  containers:
  - command:
    - snuba
    - subscriptions
    - --auto-offset-reset
    - earliest
    - --consumer-group=snuba-events-subscriptions-consumers
    - --topic=events
    - --result-topic=events-subscription-results
    - --dataset=events
    - --commit-log-topic=snuba-commit-log
    - --commit-log-group=snuba-consumers
    - --delay-seconds=60
    - --schedule-ttl=60
```
These two are in CrashLoopBackoff with OFFSET_OUT_OF_RANGE_ERROR

**Comment by chadwhitacre** [comment]
> Make Kafka lose offsets

Is it obvious how to do this? 🤔

**Comment by Antiarchitect** [comment]
@chadwhitacre Not so obvious. I'm getting this from time to time somehow. My guess is if kill Kafka pods one by one eventually you'll come to this. Moreover, I believe if this option (`--auto-offset-reset`) exists it's a pretty common case.

**Comment by chadwhitacre** [comment]
Okay, let us know if you can narrow down a consistent repro and maybe someone can chime in with some ideas.

**Comment by taxilian** [comment]
I keep hitting this as well

**Comment by chadwhitacre** [comment]
Thanks for chiming in @taxilian. I've reset the clock on this ticket, let us know if you can come up with a good repro and root cause. Last suggestion we saw from @Antiarchitect was to "kill Kafka pods one by one eventually you'll come to this." [These docs](https://docs.confluent.io/platform/current/clients/consumer.html#offset-management) are relevant, yes?

**Comment by taxilian** [comment]
The fix for this in my instance ended up being (from https://develop.sentry.dev/self-hosted/troubleshooting/#kafka) to exec into one of the kafka pods and run:

    kafka-consumer-groups.sh --bootstrap-server sentry-kafka:9092 --group snuba-events-subscriptions-consumers --topic events --reset-offsets --to-latest --execute

My best guess is that what is happening is that events are being generated faster than they are being consumed and so whatever buffer it uses eventually overruns. If that's the case then I would think the actual solution would be one of:

* Find whatever the bottleneck is and pry it open so you can process more at a time
* Find whatever the buffer is that is being overrun and make it larger so that you're (presumably) able to catch up when the spike ends.

I'm realling working with insufficient data, though. I have been seeing spikes on my postgres instance where it is getting throttled by kubernetes so that could be related (or just also related to the same thing), but I don't know. I've joined the discord server and can be found there to discuss if desired. I fully expect I'll be seeing the issue again, possibly soon -- I hadn't seen it in awhile when my relays were broken, but now that I've fixed them it hit me in under 24 hours.

**Comment by taxilian** [comment]
Sure enough, it's hit again already and now my clickhouse pods are running out of space -- presumably because it's not processing things?

**Comment by taxilian** [comment]
I'm seeing a lot of these in the sentry-ingest-consumer pod: 

```22:31:24 [INFO] batching-kafka-consumer: Flushing 100 items (from {('ingest-transactions', 0): [1413214, 1413313]}): forced:False size:True time:False
22:31:27 [INFO] batching-kafka-consumer: Worker flush took 2580ms
22:31:27 [INFO] batching-kafka-consumer: Flushing 100 items (from {('ingest-transactions', 0): [1413314, 1413413]}): forced:False size:True time:False
22:31:29 [INFO] batching-kafka-consumer: Worker flush took 2181ms
22:31:29 [INFO] batching-kafka-consumer: Flushing 100 items (from {('ingest-transactions', 0): [1413414, 1413513]}): forced:False size:True time:False
22:31:32 [INFO] batching-kafka-consumer: Worker flush took 2708ms
22:31:32 [INFO] batching-kafka-consumer: Flushing 100 items (from {('ingest-transactions', 0): [1413514, 1413613]}): forced:False size:True time:False
22:31:34 [INFO] batching-kafka-consumer: Worker flush took 2469ms```

that pod is also restarting a lot, but not in a crash loop.

the post-process-forward pod keeps crashing with this: ```%4|1641594322.059|SESSTMOUT|rdkafka#consumer-1| [thrd:main]: Consumer group session timed out (in join-state started) after 10223 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
%5|1641594325.557|REQTMOUT|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out HeartbeatRequest in flight (after 10721ms, timeout #0)
%4|1641594325.557|REQTMOUT|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1641594325.557|FAIL|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 594513ms in state UP)
%4|1641594471.061|SESSTMOUT|rdkafka#consumer-1| [thrd:main]: Consumer group session timed out (in join-state started) after 10112 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
%4|1641594504.870|SESSTMOUT|rdkafka#consumer-1| [thrd:main]: Consumer group session timed out (in join-state started) after 10499 ms without a successful response from the group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
%4|1641594551.130|SESSTMOUT|rdkafka#consumer-2| [thrd:main]: Consumer group session timed out (in join-state started) after 10276 ms without a successful response from the group coordinator (broker 2, last error was Success): revoking assignment and rejoining group
%5|1641594551.784|REQTMOUT|rdkafka#consumer-2| [thrd:GroupCoordinator]: GroupCoordinator/2: Timed out HeartbeatRequest in flight (after 10653ms, timeout #0): possibly held back by preceeding OffsetCommitRequest with timeout in 49169ms
%4|1641594551.784|REQTMOUT|rdkafka#consumer-2| [thrd:GroupCoordinator]: GroupCoordinator/2: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1641594551.784|FAIL|rdkafka#consumer-2| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 820740ms in state UP)
22:29:17 [INFO] sentry.eventstream.kafka.backend: Revoked partition assignment: [TopicPartition{topic=events,partition=0,offset=1466740,error=None}]
Traceback (most recent call last):
....
cimpl.KafkaException: KafkaError{code=UNKNOWN_MEMBER_ID,val=25,str="Commit failed: Broker: Unknown member"}
```

Something is odd, but I'm very new to this stack and I'm not sure where to look for things.

**Comment by taxilian** [comment]
Okay, after restarting all of my kafka pods one at a time things seem to be working a little more reliably... but we'll see if that continues.

Sorry for the ongoing message spam, I just figure the next poor sap to deal with this may appreciate the information

**Comment by taxilian** [comment]
... nevermind. less than an hour later the issue is back again. I don't even know what else to look at.

**Comment by chadwhitacre** [comment]
@taxilian Do you have a thread going with the helm chart maintainers as well? They may be able to provide more insight than stock self-hosted users. 🐭

**Comment by taxilian** [comment]
I don't, though perhaps I should. Mainly latched onto this one because it looks like the same issue. From what I can tell with continued testing this seems to be directly related to having too many incoming events for my infrastructure, but I have no idea how to identify the bottleneck(s). I'm decreasing the trace % and that seems to be helping, though I have some rather odd issues now which I suspect may be from all the times I've had to reset the offsets and/or blow away kafka data.
