### ISSUE TITLE
Clickhouse Cannot lock file after 21.12.0 update

### ISSUE THREAD

**Issue by husim0** [getsentry/self-hosted#1205]
### Version

21.12.0

### Steps to Reproduce

1. Update from 21.11.0 to 21.12.0

### Expected Result

Script `./install.sh` works successfully

### Actual Result

ERROR: for snuba-api  Container "cf3e4364e977" is unhealthy.
Docker container logs : 
```
 {} <Error> Application: DB::Exception: Cannot lock file /var/lib/clickhouse/status. Another server instance in same directory is already running.
```

**Comment by webmozart** [comment]
Having the same issue.

It seems to me this is caused by the rename from "onpremise" to "self-hosted". Due to this rename, the Docker container names changed from `sentry-onpremise_*` to `sentry-self-hosted_*`. When trying to start `sentry-self-hosted_clickhouse_1`, another container `sentry-onpremise_clickhouse_1` is already running and hence the lock file exists.

I could fix this by manually stopping all containers:

```

```

After that, the installation succeeds.

Once the installation is over and all new containers are running successfully, remove the old containers:

```
docker system prune --all --volumes --force
```

**Comment by husim0** [comment]
Thank you for hinting the network name change, I didn't realise it this morning (too early!).

So I ran `docker-compose down` before checking out the new branch (tag) on the git repo and that did the trick

**Comment by chadwhitacre** [comment]
Thanks for reporting @husim0 and for the solution @webmozart.
