### ISSUE TITLE
Setup Sentry SSO via SAML Keycloak does not work properly

### ISSUE THREAD

**Issue by Bibbs420** [getsentry/self-hosted#1344]
### Version

21.1.0

### Steps to Reproduce

**1. Install and start Sentry** 
- clone self-hosted sentry: https://github.com/getsentry/self-hosted/archive/refs/tags/22.2.0.zip
- starting install script `install.sh`
- Add custom user: `docker-compose run --rm web createuser --email $SENTRY_USER_MAIL --password $SENTRY_USER_PW --superuser`
- Stop container and add `system.url-prefix: 'http://localhost:9000'` to `config.yml`
- Restart all container now I've got sentry setup and can receive issues and everything
- default organization is `sentry`

**2. Setup Keycloak**
- Setting up a new client within Keycloak under the master realm
- Settings: 
   - Client ID: `http://localhost:9000/saml/metadata/sentry/`
   - Sign Assertions: `OFF`
   - Encrypt Assertions: `OFF`
   - Client Signature Required: `OFF`
   - Force POST Binding: `ON`
   - Force Name ID Format: `OFF`
   - Name ID Format: `email`
   - Valid Redirect URIs: `*`
   - Assertion Consumer Service POST Binding URL: `http://localhost:9000/saml/acs/sentry`
   - Logout Service POST Binding URL: `http://localhost:9000/saml/sls/sentry`
- Mapping Settings:
   - Add new X500 email mapper to this client
   - Set `SAML Attribute Name` to `user_email`

**3. Setup SAML2 within Sentry**
- In Sentry under `/settings/sentry/auth/` setting up SAML2
- Sentry cannot parse the xml content by giving the Metadata URL, so i copy the XML content to sentry.
- Coping the XML content from `http://localhost:8080/auth/realms/master/protocol/saml/descriptor` to Sentry GUI:
![image](https://user-images.githubusercontent.com/39264378/155320460-25d2c4ce-b22b-4403-b5a1-b24a0e749f90.png)
- Define mappings
![image](https://user-images.githubusercontent.com/39264378/155320653-2afe4bb6-2c0e-4dff-8e0b-9f708602f8a5.png)
- Now apply. Here come the problem. The redirect to `http://localhost:9000/saml/acs/sentry/` does not work. Here is the output:
![image](https://user-images.githubusercontent.com/39264378/155320999-7d4dab33-342f-43a4-b72c-2efb090bc122.png)

Also when im trying to access before setting up SAML2 `http://localhost:9000/saml/acs/sentry/` or  `http://localhost:9000/saml/sls/sentry/` nothing happens. Sentry just prints "The organization does not exist or SAML is not activated for it":
![image](https://user-images.githubusercontent.com/39264378/155321334-5fbd1ada-99c9-4de3-9368-b58660deec4b.png)

Does anyone know how to setup Sentry and Keycloak properly on my localmachine?

### Expected Result

Sentry should accept the local Keycloak instance and show the following msg:

![image](https://user-images.githubusercontent.com/39264378/155321729-9ddba264-3b23-4ce0-a948-2a5a16bd763e.png)

(Found at: https://docs.sentry.io/product/accounts/sso/saml2/)

### Actual Result

- Now apply. Here come the problem. The redirect to `http://localhost:9000/saml/acs/sentry/` does not work. Here is the output:
![image](https://user-images.githubusercontent.com/39264378/155320999-7d4dab33-342f-43a4-b72c-2efb090bc122.png)

Also when im trying to access before setting up SAML2 `http://localhost:9000/saml/acs/sentry/` or  `http://localhost:9000/saml/sls/sentry/` nothing happens. Sentry just prints "The organization does not exist or SAML is not activated for it":
![image](https://user-images.githubusercontent.com/39264378/155321334-5fbd1ada-99c9-4de3-9368-b58660deec4b.png)

Does anyone know how to setup Sentry and Keycloak properly on my localmachine?

**Comment by chadwhitacre** [comment]
You're pretty deep in it @Bibbs420, sorry I don't have any immediate ideas for you.

Presumably you [searched](https://www.google.com/search?q=sentry+keycloak) and didn't find your answer there?

**Comment by Bibbs420** [comment]
The problem is that there is no ACS route (http://localhost:9000/saml/acs/<organization_slug>/) for my sentry instance. Is this maybe not included within the self-hosted version and only a paid function?

**Comment by chadwhitacre** [comment]
I would not expect a discrepancy between SaaS and self-hosted here. Self-hosted is supposed to include all product features, though you may need to [flip a feature flag](https://develop.sentry.dev/feature-flags/) to enable something. If you don't find a relevant flag you could grep `sentry` for `acs` to investigate further.

**Comment by chou9700** [comment]
In our case, remove role_list from keycloak client scopes then everything is ok. @Bibbs420 
Keycloak -> realm -> Clients -> "sentry client" -> Client Scopes -> "remove selected"

**Comment by roock** [comment]
@Bibbs420 can you clarify which version of Sentry you are using? At the top of your initial post it says "21.1.0", but the steps to reproduce are mentioning "22.2.0"?

Additionally can you make sure that Keycloak and Sentry can reach each other? At least Sentry doesn't seem to be able to reach Keycloak (because http://localhost:9000 isn't reachable from within the sentry container.  How are you running Keycloak - also in a docker container? (Although I'm not sure if it is strictly required that Sentry and Keycloak can talk to each other directly).

**Comment by ABVitali** [comment]
Hi @Bibbs420, can I ask you if you managed to solve the issue?
I have a slightly different one but similar.

I resume here all my environment data:

Sentry:
- sentry version: 22.3.0
- single VM, docker-compose self hosted
- sentry URL: http://10.10.10.15:9000

Keycloak:
- single VM
- https://10.10.10.16/auth/realms/my-office/protocol/saml/descriptor (Notice that it is https! I added my custom ca to sentry in order to let sentry trust my keycloak instance)


I think we both followed this [guide](https://yyhh.org/blog/2020/10/how-to-setup-saml2-authentication-on-sentry-with-keycloak/)  to configure the client in keycloak and the properties in Sentry.
I'm not going to repeat all the configuration in keycloak and in Sentry since they are exactly the same you posted as your first message (of course with the addresses coherent with my setup).

My problem is that I get an error 400 from keycloak (invalid request). What is strange is that in keycloak logs I read this:
`2022-03-15 09:58:08,907 WARN  [org.keycloak.events] (executor-thread-177) type=LOGIN_ERROR, realmId=my-office, clientId=null, userId=null, ipAddress=10.10.0.11, error=client_not_found, reason=Cannot_match_source_hash`

NB: 10.10.0.11 is my laptop ip, where chrome runs, (it is a /16 subnet and all the three machines (laptop, sentryVM, keycloakVM) can talk to each other.

What is strange to my eyes in particular is the "clientId=null".
I'm trying to understand if sentry is not sending some information when clicking on the "save attributes" button.

I hope I gave enough information. Let me know if it is not the case and I'll try to complement.

**Comment by roock** [comment]
@Bibbs420 not sure how much I can help you, but we've successfully integrated Sentry and Keycloak last week.
We used version Sentry 22.03-dev and Keycloak 15.1.1.
I have the following hints for you:
- could you try to use https for Keycloak and Sentry
- if you cannot do that, check that in your realm settings you have "required ssl" set to none
- make sure to set the "Default Signature Algorithm" in the realm settings to RS256. I think I read this somewhere in a documentation that this is required. Unfortunately I cannot find the references anymore.

**Comment by slapt** [comment]
@Bibbs420 I ran into a completely similar problem. After I removed the mention of the organization (for self-hosted Sentry), everything worked:

![Keycloak](https://user-images.githubusercontent.com/8497894/161261709-f9c41fa2-906c-4256-b102-861a255bc46a.png)

**Comment by pharindoko** [comment]
> In our case, remove role_list from keycloak client scopes then everything is ok. @Bibbs420 Keycloak -> realm -> Clients -> "sentry client" -> Client Scopes -> "remove selected"


Sentry+Keycloak is working for us and I can confirm that you need to remove the role list
