### ISSUE TITLE
Rate limits for incoming transactions

### ISSUE THREAD

**Issue by webmozart** [getsentry/self-hosted#1373]
### Problem Statement

We sometimes receive massive amounts of transactions in our self-hosted Sentry instance. Is there any way to rate limit them on the server side?

### Solution Brainstorm

I know that it's possible to limit them on the client side, but unfortunately that's not a solution for us. We have one specific client in a staging environment that we want to collect 100% of transactions from, but there are sometimes spikes of 100K+ transactions which bring our Sentry down.

**Comment by aminvakil** [comment]
You can configure SDKs to sample errors and send for example half of them, but if you want to limit based on rps, you can put your sentry behind a proxy and configure rate limit on that. You'll have different options and you can configure many different ways based on different projects too.

**Comment by chadwhitacre** [comment]
Is this what you want?

https://docs.sentry.io/product/sentry-basics/tracing/distributed-tracing/#data-sampling

**Comment by webmozart** [comment]
@aminvakil Thanks for the tip about the proxy. Do you have any recommendation for that?

Out of curiosity: Sentry shows the number of "dropped" transactions in the UI. Based on what criteria are those transactions dropped? I couldn't find any information about that in the docs.

@chadwhitacre No, as I wrote I would like to rate limit on the server side. Thanks anyway for your help!

**Comment by chadwhitacre** [comment]
Hrm, sorry didn't notice that was client-side. We're talking a lot about (server-side) dynamic sampling internally, I figured that meant we have _non_-dynamic sampling server-side already, but maybe not? 🤔

**Comment by chadwhitacre** [comment]
I've asked internally.

**Comment by chadwhitacre** [comment]
@aminvakil You were right after all. :)

**Comment by aminvakil** [comment]
Just keep in mind that some sentry SDKs (I've seen this on Android) we'll try again if there is an error reaching sentry server.

AFAIK it will try again after a timeout or 5xx errors, so when I want to drop a specific user or all users for any reason or testing, I will just return 200 to them on edge before reaching sentry, so I would be sure they won't try again later.

I have not tested 4xx errors though, maybe you can misuse 429 (Too many requests) (it's a misuse as it should be returned if one user sends too many requests) or 403 or whatever you see fit. You can test easily (and share with us :)) if sentry tries again hitting a 4xx error.

Otherwise they'll keep trying again and again (although AFAICS they won't retry after 3 retries, probably that can be configured too) to reach sentry server and your load will become heavier after a while :)

**Comment by chadwhitacre** [comment]
Thanks for posting back @webmozart! Glad you were able to figure this out.

We good to close here, then?
