### ISSUE TITLE
deployment options other than docker?

### ISSUE THREAD

**Issue by apachelogger** [getsentry/self-hosted#1392]
### Problem Statement

Hello from [KDE](https://kde.org) :)

We are currently looking to evaluate sentry and were wondering if there are any deployment options other than a tangle of docker containers - specifically our sysadmins would feel more excited about a tangle of systemd units. Any plans? Alternatively if one were to create them would they be acceptable upstream?

**Comment by chadwhitacre** [comment]
Short answer is no, we have no plans to move away from Docker Compose (we do have [a Podman ticket](https://github.com/getsentry/self-hosted/issues/369) languishing in the backlog but that wouldn't really help you). The reason is that this repo is designed for low-volume deployments and proofs of concept. From [the docs](https://develop.sentry.dev/self-hosted/):

> This repository also serves as a blueprint for how various Sentry services connect for a complete setup, which is useful for folks willing to maintain larger installations.

If you get something working with systemd, feel free to share your experience here for folks who find this ticket in the future. In the meantime, I'm going to go ahead and close this out. 🙏

(P.S. Sorry for the late reply, I was OOO.)
