### ISSUE TITLE
Installation script aborts due to an python error

### ISSUE THREAD

**Issue by MrSnoop** [getsentry/self-hosted#1481]
### Version

22.5.0 nightly

### Steps to Reproduce

Download git repository
execute ./install.sh

Two errors are thrown during installation:

```
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
```

### Expected Result

Installation runs through.

### Actual Result

```
Error: It looks like you've skipped a hard stop in our upgrade process. Please follow the upgrade process here: https://develop.sentry.dev/self-hosted/releases/#hard-stops
An error occurred, caught SIGERR on line 1
```

**Comment by aminvakil** [comment]
It's a warning and it's safe to ignore.
Also this is a duplicate of https://github.com/getsentry/self-hosted/issues/1333.

**Comment by aminvakil** [comment]
Sorry, I overlooked, the error you have been a pasted is just a warning.

Please paste the full output of `./install.sh`.

**Comment by MrSnoop** [comment]
Follow up: 
I ran into two issues after all. Solving it was quite hard, as the description of the errors did not make too much sense.
However, I upgraded Ubuntu and then switched to docker compose v2. Hence installing docker compose 2 it does not switch `docker-compose` command to v2 automatically. You can check that by comparing `docker-compose -v` and `docker compose -v` (not the space). But there is a nice library https://github.com/docker/compose-switch which does the trick.

**Comment by aminvakil** [comment]
We have a script in self-hosted which first checks for `docker compose` (v2) existence and if so, it would use it, if not, it would fall back to `docker-compose`.

Also a couple of notes unrelated to self-hosted:

- You shouldn't keep both `docker-compose` v1 and `docker-compose` v2 on your server.
- Since [v2.0.1](https://github.com/docker/compose/releases/tag/v2.0.1) `docker-compose` can run as a standalone program, so you can create a symlink from `/usr/local/bin/docker-compose` to `/usr/libexec/docker/cli-plugins/docker-compose`, and if your `$PATH` contains `/usr/local/bin` which it does by default in most operating systems, you can use `docker-compose` instead of `docker compose` if you're more familiar with.
