### ISSUE TITLE
Transfering Audit logs to Splunk

### ISSUE THREAD

**Issue by ozankyncu** [getsentry/self-hosted#1741]
### Problem Statement

Hello,
We want to regularly transfer audit logs to Splunk via Sentry on premise. We tried the "docker-compose logs web" command, but we saw that all the logs came. It is sufficient for us to transfer only the logs in the "audit-log" tab.

We tried to use the sentry_auditlogentry table in the Sentry database. But the logs here are kept encrypted.

Is there a method you recommend for transferring the logs from the audit-log tab to Splunk?
Best regard

**Comment by hubertdeng123** [comment]
I dug up two previous threads on this if that's helpful.

https://forum.sentry.io/t/how-to-access-audit-logs-to-get-user-actions-traceback/8209/3
Would changing the logging format to JSON be easier for you to parse through them? 

Otherwise, it looks like we only have web container logs, but you can change the default role there
https://github.com/getsentry/self-hosted/issues/1366
