### ISSUE TITLE
Sentry Relay error handling request: failed to queue envelope   caused by: envelope buffer capacity exceeded

### ISSUE THREAD

**Issue by PAKalucki** [getsentry/self-hosted#1929]
### Self-Hosted Version

23.1.0

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

2.14.1

### Steps to Reproduce

docker-compose up -d

### Expected Result

Sentry should be getting new errors and transactions

### Actual Result

Self-hosted Sentry is not getting any new errors/transactions, I've checked all service logs and found

Relay service log is flooded with below errors:
```
2023-01-20T18:17:33Z [relay_server::actors::project_upstream] ERROR: error fetching project state 31f03f965d5840d18b1ae70526e59150: deadline exceeded  

2023-01-20T18:17:33Z [relay_server::utils::envelope_context] ERROR: dropped envelope: invalid data (project_state)  

2023-01-20T18:17:33Z [relay_server::endpoints::common] ERROR: error handling request: failed to queue envelope  
caused by: envelope buffer capacity exceeded  
```

Nginx service log is flooded with 403 and 503 errors:
```
"POST /api/3/envelope/ HTTP/1.1" 403 64 "-" "sentry.python/1.9.10"

"POST /api/3/envelope/ HTTP/1.1" 503 84 "-" "sentry.python/1.9.10"
```

Restarting all Sentry services is not helping, what can I do here?

**Comment by hubertdeng123** [comment]
Seems like this may be related to https://github.com/getsentry/self-hosted/issues/1927. Thanks for bringing this up

**Comment by jan-auer** [comment]
The issue here is that Relay is not able to retrieve information from Sentry and starts to build a queue of incoming requests while waiting for it. This queue is capped and eventually overflows, which leads to the reported error. You will also observe 503 responses from Relay.

The "deadline exceeded" error shows the culprit: Relay times out while waiting for info on your projects. Do you see any errors in the Sentry `web` container? Particularly, please verify if these two required celery tasks are running properly:
- `sentry.tasks.relay.build_project_config`
- `sentry.tasks.relay.invalidate_project_config`

---

**Side notes:**

The default queue size for relay is set to a low amount of 1000 requests. If you have a lot of traffic, you may want to increase it in your `config.yml`:

```yaml
cache:
  envelope_buffer_size: 1000000,  # queue up to 1 million requests
```

This is completely unrelated to #1927.

**Comment by matthewbyrne** [comment]
We're have the same issue. Our `web` container only has `INFO` `WARNING` logs, no errors.

How can I check the 2 required celery tasks are running properly?

**Comment by jan-auer** [comment]
Alright, thanks. There are two things you  can do to verify celery tasks are running: 

 1. Check the `worker` container for errors, that's where they are supposed to be running. 
 2. Check celery queues for backlogs. In default configuration, we [use redis as backend](https://github.com/getsentry/self-hosted/blob/19d6edfae05ab5386fe13529465d711ae1f2ed2e/sentry/sentry.conf.example.py#L93-L95), so you can use [these commands](https://docs.celeryq.dev/en/stable/userguide/monitoring.html#redis) to check for backlogs. The related queues are called `relay_config` and `relay_config_bulk`. 
 
Alternatively for 2, [Flower](https://docs.celeryq.dev/en/stable/userguide/monitoring.html#flower-real-time-celery-web-monitor) might provide more insights into celery, though I would propose to check the other two first. 

Thanks!

**Comment by PAKalucki** [comment]
FYI it started working again after some time without any action on my side
