### ISSUE TITLE
Migrate README content to dev docs

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1996]
Silly and confusing to have two sources of truth. Let's consolidate on dev docs.

https://github.com/getsentry/self-hosted#readme ⇒
https://develop.sentry.dev/self-hosted/

**Comment by aldy505** [comment]
Me and @BYK talked about this a while ago on Discord (link https://discord.com/channels/621778831602221064/796028405833007104/1250449735815401704) since we have two docs in which I think people don't really read the docs on the develop website. 

So what I wonder about are: 
1. Which part of the self-hosted documentation should we sync, between the develop docs site and the repo's README?
2. Or.. should we nuke the README on the repository and point people to go to the website? But I don't think this route is a good idea.

cc @hubertdeng123 @azaslavsky

**Comment by aldy505** [comment]
Another ping, what do you guys think about that :point_up:? I need your opinions before we actually move forward and clean up current documentation mess @hubertdeng123 @azaslavsky
