### ISSUE TITLE
Disable self-registration and enable "Request to join"

### ISSUE THREAD

**Issue by Sebbo94BY** [getsentry/self-hosted#2071]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

19.03.13

### Docker Compose Version

19.03.13

### Steps to Reproduce

1. Setup Sentry
2. Visit the Sentry login page
3. You can see the "Sign In" and "Register" tab

### Expected Result

Instead of the "Register" tab, I expect to see the "Request to join" button.

### Actual Result

Instead of the "Request to join" button I see the "Register" tab.

![image](https://user-images.githubusercontent.com/5154682/230345575-15895867-0db1-4f7e-9aed-ed336152e24b.png)

Additional notes:

- The Sentry version 23.1.1 had a "Request to join" button, which was not working due to this issue: https://github.com/getsentry/sentry/pull/43892
- We have upgraded our Sentry from version 23.1.1 to 23.3.1 and since then the UI changed - no config were changed.
- The Sentry version 23.3.1 doesn't have the "Request to join" button anymore.
- The "Register" tab causes on our side the problem, that any user can register by their own without the need for an admin to allow it. Previously, with the "Request to join" button an admin had to allow the user registration. => In our case Sentry is only internally reachable, but for others it's maybe reachable over the public internet and thus a problem for the ISO 27001 certification.

Additional, even when we set / disable the following configs, it doesn't change anything - the users can still register without any approval by an admin - they even get directly logged in to the application after the registration:

- https://sentry.example.com/settings/sentry/security-and-privacy/ => Allow Join Requests: Disabled / Enabled
- https://develop.sentry.dev/config/#authentication `config.yaml` => `auth.allow-registration`: False / True

**Comment by hubertdeng123** [comment]
Interesting, I don't seem to be able to replicate this. The allow join requests should enable/disable the `Request to Join` button. Can you check your postgres database? I'm wondering what the value of `auth.allow-registration` is in the `sentry_option` table

**Comment by Sebi94nbg** [comment]
Thanks for your reply @hubertdeng123 !

Seems like as it hasn't been updated since a while, although we changed it in the `config.yaml` and restarted the container afterwards:
```
$ docker-compose exec postgres psql -U postgres -d postgres -c "SELECT * FROM "sentry_option" WHERE key = 'auth.allow-registration';"
 id |           key           |  value   |         last_updated          
----+-------------------------+----------+-------------------------------
  9 | auth.allow-registration | gAKJLg== | 2020-10-13 07:46:00.806419+00
(1 row)
```

**Comment by Sebi94nbg** [comment]
@hubertdeng123 Something seems to be buggy.

We are managing the installation, configuration and upgrade of Sentry with Ansible, so both of our instances (test + production) are 100 % identical - except of the hostname, domain and the AWS EC2 instance type (TEST uses the same type, but a smaller one than PROD).

I've now rolled out our current configuration in both environments and also ensured, that all config files are identical (using a `diff`). Also the settings in the UI are identical.

TEST shows now this:

![image](https://user-images.githubusercontent.com/5154682/234007968-d32772e1-b7af-4380-b225-9043dd3ec75a.png)

PROD shows this:

![image](https://user-images.githubusercontent.com/5154682/234008047-21635638-32c7-4989-b75a-c0688ed312a0.png)

So the before missing `Request to Join` menu is now visible and also useable. However, nobody changed anything since I've created this issue here. :confused: 

However, in TEST I see the "Register" tab, in PROD not. The only difference is the value in the Postgres database:

TEST:
```shell
$ docker-compose exec postgres psql -U postgres -d postgres -c "SELECT * FROM "sentry_option" WHERE key = 'auth.allow-registration';"
 id |           key           |  value   |         last_updated          
----+-------------------------+----------+-------------------------------
  3 | auth.allow-registration | gAKILg== | 2020-12-16 08:14:17.862984+00
(1 row)
```

PROD:
```shell
$ docker-compose exec postgres psql -U postgres -d postgres -c "SELECT * FROM "sentry_option" WHERE key = 'auth.allow-registration';"
 id |           key           |  value   |         last_updated          
----+-------------------------+----------+-------------------------------
  9 | auth.allow-registration | gAKJLg== | 2020-10-13 07:46:00.806419+00
(1 row)
```

The option `auth.allow-registration` is NOT configured in the `sentry/config.yml` of any system, so it should be for both systems the default (`False`). See https://develop.sentry.dev/config/#authentication for further information.

```shell
$ grep -i "allow-registration" sentry/config.yml 
$
```

I've manually updated the value in the TEST Postgres database to the same as in PROD:
```shell
$ docker-compose exec postgres psql -U postgres -d postgres -c "UPDATE "sentry_option" SET value='gAKJLg==' WHERE key = 'auth.allow-registration';"
UPDATE 1
```

```shell
$ docker-compose exec postgres psql -U postgres -d postgres -c "SELECT * FROM "sentry_option" WHERE key = 'auth.allow-registration';"
 id |           key           |  value   |         last_updated          
----+-------------------------+----------+-------------------------------
  3 | auth.allow-registration | gAKJLg== | 2020-12-16 08:14:17.862984+00
(1 row)
```

Next I have restarted the TEST Sentry application to take effect of this change:

```shell
docker-compose restart
```

Afterwards, the "Register" tab was also removed from the TEST instance.

=> Reported problem solved / workarounded: Self-registration is now disabled and "Request to Join" is enabled.

=> Question to clarify: Is there an issue with updating the values in the Postgres database and/or reloading these changes in the Sentry UI?

**Comment by Sebi94nbg** [comment]
@hubertdeng123 any news from your side here? Anything else, what I can check?
