### ISSUE TITLE
Upgrade fails with - install/error-handling.sh: line 68: /usr/bin/docker: Argument list too long

### ISSUE THREAD

**Issue by djmartin67** [getsentry/self-hosted#2103]
### Self-Hosted Version

23.3.0

### CPU Architecture

x86_64

### Docker Version

 20.10.5+dfsg1

### Docker Compose Version

1.28.6, build 5db8d86f

### Steps to Reproduce

Upgrade 23.3 - to 23.4.0

Run install.sh script

### Expected Result

install to complete

### Actual Result

This is a standard install - no customisation. 

[sentry_install_log-2023-04-24_08-42-42.txt](https://github.com/getsentry/self-hosted/files/11308805/sentry_install_log-2023-04-24_08-42-42.txt)

install/error-handling.sh: line 68: /usr/bin/docker: Argument list too long

**Comment by hubertdeng123** [comment]
What is the container name for your postgres instance? Is it `sentry-self-hosted_postgres_1`? You may need to run that part of the `upgrade-postgres.sh` script manually with that instead of `sentry-self-hosted-postgres-1`. This is on me, I put in a fix for that but it is not available in 23.4.0

Fix: https://github.com/getsentry/self-hosted/pull/2096
