### ISSUE TITLE
Add Spike Protection

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#2122]
https://docs.sentry.io/product/accounts/quotas/spike-protection/

See #1993 and #1838 for parallel cases.

**Comment by aldy505** [comment]
I don't see why this is helpful on self-hosted, as every event never got dropped unless I set them to (via the "Delete and discard future events" button)

**Comment by antonpodolsky** [comment]
@aldy505 At scale, spikes in error reports are choking our self-hosted Sentry backend and require continuous tweaking of resource limits.

**Comment by aldy505** [comment]
@antonpodolsky May I know your machine configuration and how much traffic is going through your instance?

**Comment by antonpodolsky** [comment]
@aldy505 Traffic is several millions hourly reports. Regarding the actual setup, I understand that it's a bit elaborate, so not sure I can share it here in a concise way.

**Comment by Aulig** [comment]
> I don't see why this is helpful on self-hosted, as every event never got dropped unless I set them to (via the "Delete and discard future events" button)

I normally get <200 events per hour. Recently some kind of bug is suddenly sending 4000 events in a very short time, which is taking down my entire sentry instance (8GB ram, 4 CPU cores). My server load jumps to 280 or whatever and sometimes I can't even SSH in anymore. A simple server reboot doesn't solve it either, since it seems like Redis crashes completely, so it doesn't get restarted on server reboot. I need to manually shut down the docker containers and start them again.

When the Sentry instance goes down, it massively slows down my website (since the sentry error handling script needs to be loaded early in the HTML), since browsers attempt to wait for the sentry script to load (which it doesn't, so it waits until the timeout).

Having this happen every 12-48 hours is no fun ;)

**Comment by hubertdeng123** [comment]
From enterprise team,
> spike protection is in getsentry, which iirc is not available to self-hosted. we use subscription information (quotas) to determine spike thresholds

@chadwhitacre I don't think it's possible to enable this for self-hosted

**Comment by aldy505** [comment]
For everyone else, it seems we might need to add rate limiting on the nginx.conf ourselves.

Talked to Michi and Hubert at Discord, this feature is not feasible for maintaining in-app processed rate limiting for incoming events on self-hosted. It's only effective on SaaS.
