### ISSUE TITLE
restore.sh only restores one DSN of a project

### ISSUE THREAD

**Issue by jansorg** [getsentry/self-hosted#2450]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. I created a project with two different DSNs "Exceptions" and "Events"
1. I created a backup with `./scripts/backup.sh`
4.  Reset the installation with `./scripts/reset.sh` to verify the backup
5. `./scripts/restore.sh`

### Expected Result

The restored system should have the identical settings.
The project should have to the two DSN it originally had.

### Actual Result

The project has only one DSN.

I'm not sure what you need to debug this. I had the same issue when I tried to restore from a backup created with an earlier version.

**Comment by azaslavsky** [comment]
Interesting - would it be possible to provide the minimal steps to reproduce on a new install? You just run `./install.sh`, create an org, create a project, add a second DSN, backup, restore, and only one appears?

**Comment by jansorg** [comment]
Yes, that was what I did.
At least for me, the backup and restore cycle was badly broken with 23.9.1. The data created by `install.sh` included the internal org, which was also included in the backup.json created by `backup.sh`. Now, when I attempted to restore in a clean database after `reset.sh`, apparently the internal org was still in the database and `restore.sh` attempted to create it again. The follow up of that was that the DSNs created for other orgs had a different ID for the org (which is part of the DSN, I think). I had to remove the internal org from backup.json to make it work.

I'll try to run a fresh install with the steps above and post the results after I create two DSNs.

**Comment by azaslavsky** [comment]
I'm sorry you're experiencing that! The new restore script is working as expected (see 23.9.1 release notes) in that it strives to be as undestructive of existing data as possible - hence the new org with new DSNs.

I think the crux of the issue is that reset.sh seems to not be deleting the underlying data - can you check that the associated docker volumes, and their contained files, are being removed? If the reset script works properly, and the database is truly cleaned out, you should be able to do a restore.
