### ISSUE TITLE
DSN in Projects for using in SDKs is set by Sentry URL and not by Relay URL

### ISSUE THREAD

**Issue by mmojzis** [getsentry/self-hosted#2653]
### Self-Hosted Version

23.11.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.23.1

### Steps to Reproduce

1. Have Relay on different domain than sentry. For example we have relay opened to the world and sentry not. And we manage that by using different domain.
2. Get project's DSN

### Expected Result

DSN of sentry is configurable 

### Actual Result

Project DSN uses Sentry URL so we have to manually change domain in copied each time we want to setup SDK for a project.
I found no way in the config how to change it.

**Comment by hubertdeng123** [comment]
Unfortunately, the DSN of sentry is not configurable. This is not something we're looking to support, so you'll need to manually change the domain whenever you copy it from a project. You can play around with `system.url-prefix` if you'd like, but that might mess up other areas of your self-hosted instance so that is not recommended.
