### ISSUE TITLE
self host ，Which configurations have been modified to enable the use of one's own clickhouse cluster

### ISSUE THREAD

**Issue by ggbondoh** [getsentry/self-hosted#2763]
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

23.0.0

### Docker Compose Version

2.23.0

### Steps to Reproduce

!

### Expected Result

!

### Actual Result

!

**Comment by aldy505** [comment]
Hello, reading from the title, you wanted to use your own ClickHouse Cluster to store Sentry data?

If that's the case, for self-hosted, as far as I know, there's no possible way to configure ClickHouse cluster, you can only do a single node ClickHouse connection. 

But, since I don't have any knowledge on reading Snuba (the part of Sentry that connects to ClickHouse) source code, I think you might get lucky with configuring these settings on Snuba's container environment variables:

https://github.com/getsentry/snuba/blob/cc0002f39113e043d47c34a5c9f3db6189c58ffb/snuba/settings/settings_distributed.py#L5-L14

Configure the environment variables here:

https://github.com/getsentry/self-hosted/blob/302b22b7a51e54236aec8db7978c39b07d51c717/docker-compose.yml#L91-L100

I don't think I can assist any further, you'd need to ask around to the employee on the [getsentry/snuba](https://github.com/getsentry/snuba/issues) repository.
