### ISSUE TITLE
Sentry self-hosted latest version supports external PostgreSQL DB version 14 or not.

### ISSUE THREAD

**Issue by amitesh2181763** [getsentry/self-hosted#3074]
### Self-Hosted Version

24.4.2

### CPU Architecture

x86-64

### Docker Version

20.10.25

### Docker Compose Version

2.19.0

### Steps to Reproduce

NA

### Expected Result

Just want to know external PostgreSQL version 14 supporting by Sentry or not.

### Actual Result

NA

### Event ID

NA

**Comment by aldy505** [comment]
If by "supported by sentry" translates to "Can I use an external Postgres 14 rather than the one that's bundled with the Docker Compose file?" then yes, you can.

But... the OSPO team (the one who manages this repo) can't help with anything regarding config or troubleshooting if there are any errors. It's kinda too much unknowns that we need to maintain (if we're ever to do that). You're still free to use external Postgres though, but you're on your own. You can still ask around at sentry (the [getsentry/sentry](https://github.com/getsentry/sentry) repo) for finding some answers regarding this.

Hope that answers. Let me know if you have further questions.
