### ISSUE TITLE
Upgrading Self Hosted Sentry to New Version 24.6.0 is Causing Issue

### ISSUE THREAD

**Issue by Swaroop-1613** [getsentry/self-hosted#3168]
### Self-Hosted Version

24.5.1

### CPU Architecture

x86_84

### Docker Version

20.10.25

### Docker Compose Version

v2.19.1

### Steps to Reproduce

We tried upgrading Sentry to the latest version 24.6.0 in our test environment. While upgrading, we encountered with the below error 
`Error in install/upgrade-clickhouse.sh:15.
'$dc up -d clickhouse' exited with status 1
-> ./install.sh:main:25
--> install/upgrade-clickhouse.sh:source:15
Cleaning up...`

We tried going back to the previous version - 24.5.1 but we were encountering the below error:

`Error response from daemon: Container ****************** is restarting, wait until the container is running
Error in install/upgrade-clickhouse.sh:21.
'version=$($dc exec clickhouse clickhouse-client -q 'SELECT version()')' exited with status 1
-> ./install.sh:main:25
--> install/upgrade-clickhouse.sh:source:21
Cleaning up...
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1`

### Expected Result

We need to upgrade the Self Hosted Sentry Application from 24.5.1 to 24.6.0.

### Actual Result

Please find the below screenshots for the same:

![image](https://github.com/getsentry/self-hosted/assets/173468575/7a69beea-3477-4765-b8ba-2c810ce60367)

<img width="554" alt="Screenshot 2024-06-26 113217" src="https://github.com/getsentry/self-hosted/assets/173468575/57890f05-4db9-4597-8b8f-6fde498c0afe">

**Comment by Swaroop-1613** [comment]
Hey @hubertdeng123 could you please help us with the issue.
Thanks in advance

**Comment by hubertdeng123** [comment]
If you are upgrading your sentry instance, why is sentry-kafka missing? Is it perhaps named something else? Or did you end up removing the docker volume before upgrading?

**Comment by TimShilov** [comment]
The OP mentioned the upgrade, but I have just encountered the same error on 24.5.1 without even trying to upgrade.
The Sentry was working fine for weeks after the last upgrade and then suddenly stopped (it sometimes happens when we have a spike of events).

Usually, in this case I use [the Nuclear option](https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option) mentioned in the docs, and that worked for me multiple times before. It seems that since 24.5.1 something in the installation scripts has changed, and now this option isn't working and causing the above-mentioned issue because the init script requires volumes to exist and the "nuclear option" requires you to remove them before running `install.sh`.

I have worked around that by simply creating the volumes back before running `./install.sh`, everything seems to be working fine, and I could update to 24.6.0 afterwards as well without any issues.
```shell
docker volume create --name=sentry-kafka
docker volume create --name=sentry-zookeeper

./install.sh
```

**Comment by joshuarli** [comment]
We should move `source install/create-docker-volumes.sh` before `source install/upgrade-clickhouse.sh`  in install.sh, I'll put up a PR soon after I'm done triaging some more stuff.

**Comment by joshuarli** [comment]
closing; you need to create these volumes before running install.sh, as we're not sure how those volumes get deleted

```
docker volume create --name=sentry-kafka
docker volume create --name=sentry-zookeeper
```

feel free to reopen if you encounter more issues!
