### ISSUE TITLE
Release 24.9.0

### ISSUE THREAD

**Issue by joshuarli** [getsentry/self-hosted#3271]
[previous 24.8.0](https://github.com/getsentry/self-hosted/issues/3203) | ***24.9.0*** | [next 24.10.0](https://github.com/getsentry/self-hosted/issues/3328)

- [x] Release all components (_replace items with [publish repo issue links](https://github.com/getsentry/publish/issues)_).
  - [x] https://github.com/getsentry/publish/issues/4322
  - [x] https://github.com/getsentry/publish/issues/4324
  - [x] https://github.com/getsentry/publish/issues/4326
  - [x] https://github.com/getsentry/publish/issues/4325
  - [x] https://github.com/getsentry/publish/issues/4323
- [x] Release self-hosted.
  - [x] https://github.com/getsentry/publish/issues/4327
  - [x] Check to make sure the new release branch in self-hosted includes the appropriate CalVer images.
  - [x] Accept (publish) the release.
  - [x] Edit [release notes](https://github.com/getsentry/self-hosted/releases).
- [x] Follow up.
  - [x] [Create the next release issue](https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&projects=&template=release.yml) and link it from this one.
    - _replace with link_
  - [x] Update the [release issue template](https://github.com/getsentry/self-hosted/blob/master/.github/ISSUE_TEMPLATE/release.yml).
  - [ ] https://github.com/getsentry/sentry/pull/77676

**Comment by aldy505** [comment]
Don't forget to remind people to upgrade to 24.8.0 before going for 24.9.0, since 24.8.0 is a hard-stop https://github.com/getsentry/sentry-docs/pull/11146

**Comment by theneva** [comment]
I'm curious about the `Release self-hosted` list. The tag was released 11 hours ago, and the first task (pointing to https://github.com/getsentry/publish/issues/4327) is checked off – but the third task (`Accept (publish) the release`) is still unchecked, and the issue is still open.

What's the difference between those two tasks – and when should I consider it "safe" to upgrade?

(Sorry to any subscribers to this issue who don't care about this; I couldn't find a better place to ask.)
