### ISSUE TITLE
When do new cloud features get merged into self-hosted? I see that Uptime Monitoring was released for early adopters

### ISSUE THREAD

**Issue by edgariscoding** [getsentry/self-hosted#3301]
### Problem Statement

https://changelog.sentry.dev/changelog/uptime-monitoring-early-adopters-release/

I noticed that Uptime Monitoring was released to early adopters of Sentry cloud on August 15, 2024. 

It looks like self hosted version `24.8.0` was released on August 15, 2024 as well. Does this version include uptime monitoring under the early adopters flag as well?

**Comment by aldy505** [comment]
Usually when they're on General Availability. But you can always see upcoming stuff here: https://github.com/getsentry/self-hosted/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22Type%3A%20Pre-release%20Feature%22

I haven't asked around on configuring uptime monitoring, it'll take some time since there's a Kafka topic need to be configured (meaning we need to add either snuba consumer or sentry worker) and a new [uptime-checker](https://github.com/getsentry/uptime-checker) service that don't have a public Docker image yet.

**Comment by aldy505** [comment]
I'm closing this, moving the Uptime Monitoring here https://github.com/getsentry/self-hosted/issues/3304
