### ISSUE TITLE
Caches, Queues, LLM Monitoring

### ISSUE THREAD

**Issue by leshik** [getsentry/self-hosted#3317]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

27.2.1

### Docker Compose Version

2.29.2

### Steps to Reproduce

Hi!

I have two identical Sentry instances installed, both `24.8.0`. One (working) was freshly installed, and another one (with issues) was gradually upgraded from `24.6.0`. First shows the correct welcome screen with "Read the docs" button on Caches, Queues, and LLM Monitoring pages. The second one shows "You don't have access to this feature" on all 3 insights pages. Sentry configuration is identical.

What should I do?

### Expected Result

Identical behavior in both instances.

### Actual Result

The behavior differs.

**Comment by aldy505** [comment]
A few things that you should make sure of:

On the `sentry.conf.py` file, make sure you have these features flag added:
https://github.com/getsentry/self-hosted/blob/b8b4aa20aa7aa4e37a8a2569d70ca54d450ae947/sentry/sentry.conf.example.py#L296-L324

Since a few versions ago (forgot which one), Sentry introduces an "errors-only" mode, so that's just plain old Sentry which acts as a error monitoring software. You should also add this line on your `sentry.conf.py`:
https://github.com/getsentry/self-hosted/blob/b8b4aa20aa7aa4e37a8a2569d70ca54d450ae947/sentry/sentry.conf.example.py#L384-L385

If you have `.env.custom` file, make sure to add this line (and while you're there, make sure the Docker tag version is correct):
https://github.com/getsentry/self-hosted/blob/b8b4aa20aa7aa4e37a8a2569d70ca54d450ae947/.env#L2

After all that, re-run the `./install.sh` script.

Let me know if that fixed it for you.

**Comment by noma4i** [comment]
@aldy505 good one. I hope that will be reflected in the documentation at some point.

**Comment by leshik** [comment]
@aldy505 this helped, thanks!

Basically it means that we have to keep our changes to configs somewhere, and then on each upgrade to re-create configs from scratch with our changes instead of keeping existing ones.

**Comment by aldy505** [comment]
> Basically it means that we have to keep our changes to configs somewhere, and then on each upgrade to re-create configs from scratch with our changes instead of keeping existing ones.

Ah no, basically you'll need to do a few git diff to the config you're in. I don't recommend recreating every config for each upgrades.

**Comment by aldy505** [comment]
Since I assume this has been fixed, I'll close the issue for now. Feel free to open up a new one when another problem arises.
