### ISSUE TITLE
High memory usage by Kafka - new install

### ISSUE THREAD

**Issue by afonsosantos** [getsentry/self-hosted#3324]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

27.2.0

### Docker Compose Version

2.29.2

### Steps to Reproduce

1. Do a fresh install of Sentry self hosted on a Debian 12 VM (4 vCPU, 16GB RAM, 100GB SSD)
2. Observe the memory usage spike up to 13GB (this VM is dedicated to Sentry)  

### Expected Result

The memory usage should be lower (?)

Some context:
- I have 6 projects already configured, but only 1 of them is sending data to Sentry (around 1 error per day).
- Only 1 user on the installation
- The VM is a in-house VM on VMware ESXi

### Actual Result

Output from `htop`:

![Image](https://github.com/user-attachments/assets/704e4cbe-ba63-4e08-9311-bdda259d7490)

**Comment by aldy505** [comment]
That is normal. No matter throughput you're in, Kafka will always consume high RAM resource. Nothing you can do about that.

Or.. replace Kafka with Redpanda, which is a Kafka rewritten in C++, it's drop in compatible. But it won't be implemented on the upstream self-hosted repo (this repo) since the sentry.io's infra setup is using Apache Kafka.

**Comment by afonsosantos** [comment]
OK, so I bumped the server RAM and CPU resources to 32 GB and 8 vCPUs and the RAM usage seems to be stable at around 15GB for now.

Seems like the 16GB should of RAM is really the minimum requirement just for starting Sentry.

Thanks for all the input, closing this for now.
