### ISSUE TITLE
Event data was getting dropped in relay

### ISSUE THREAD

**Issue by sree-warrier** [getsentry/self-hosted#3335]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

na

### Docker Compose Version

na

### Steps to Reproduce

Events were getting dropped at the relay side also we were facing issue with envelope buffer size limit. Is there any setting at relay side to controlling the event size and payload under a event ? 

How we can check the payload of a event coming to sentry, does we get a accumulated value of common errors with the size of a event with payload. We know that event size depends on the breadcrumbs and dependencies and other configuration setting of app. 

How can restrict the size of data at relay side if an event payload i having more than a limit. 

### Expected Result

NA

### Actual Result

NA

### Event ID

NA

**Comment by aldy505** [comment]
The default envelope size is 50 MB (see https://docs.sentry.io/product/relay/options/#size-limits, config key is `limits.max_envelope_size`), this should be restricted on each SDK. The maximum buffer size for envelope is 1000 (config key is `cache.envelope_buffer_size`), so in total it's 1000 * 50 MB (= 50 GB stored in memory). But you might also want to look at the spooling config (https://docs.sentry.io/product/relay/options/#spooling)

Usually the problem is caused by either:
1. `relay` having a hard time publishing that events to Kafka. Probably slow disk speed or low RAM.
2. The event throughput is too high, if this is the case, you can spawn a few replica of the `relay`, but bear in mind you'll also need to increase your server (or VM) specs.

**Comment by sree-warrier** [comment]
@aldy505 is there a way in UI or metric API to check per event payload size ?

**Comment by aldy505** [comment]
> [@aldy505](https://github.com/aldy505) is there a way in UI or metric API to check per event payload size ?

@sree-warrier I don't think there is. Although there's this button that you can see when you browse errors or spans on the detailed view. ![Image](https://github.com/user-attachments/assets/e58c1cd4-6fb5-43ec-b2b2-3129d5aa0aa4)

I don't know if that's the correct size of the event payload. I assume it's not though.

**Comment by sree-warrier** [comment]
@aldy505 is there any configs we can set it at relay side to limit the payload size. Any event more that particular size will be dropped and shouldn't be processed. Was able to go through the size-limit docs of sentry, but unable to find the configs for those. If there are any configs do share.

**Comment by aldy505** [comment]
> [@aldy505](https://github.com/aldy505) is there any configs we can set it at relay side to limit the payload size. Any event more that particular size will be dropped and shouldn't be processed. Was able to go through the size-limit docs of sentry, but unable to find the configs for those. If there are any configs do share.

@sree-warrier I got back from the Relay team, they said it's there on the size-limits.

![Image](https://github.com/user-attachments/assets/8b0cbcf5-7f10-4f93-b6b0-c1bd0d9bfb2d)
