### ISSUE TITLE
Performance: All Events tab on issue with many events loads indefinitely

### ISSUE THREAD

**Issue by Tim-Blyth-SiteHost** [getsentry/self-hosted#3413]
### Environment

Self-hosted (24.6.0)

### Steps to Reproduce

1. Open issue with many events
2. Click "All Events"
3. Wait for first page of events to load... (60s have passed for Showing 50 of 7,988 events and still a spinner)

I am unsure if the number of environments is a contributing factor, but I have 20 environments, with "All Envs" selected.

### Expected Result

First page of All Events loads in a reasonable time.

### Actual Result

![Image](https://github.com/user-attachments/assets/e26b1bda-e3ab-4183-8e6c-3a8f5088529d)

The spinner seems to be indefinite, it has been minutes now. Slowness seems to scale exponentially with number of events, or perhaps total events in the selected environments.

### Product Area

Issues

### Version

24.6.0

**Comment by BYK** [comment]
@Tim-Blyth-SiteHost do you have any logs you can share with us please?

**Comment by lorado** [comment]
hey @Tim-Blyth-SiteHost 
I just had similar issue, in my situation API requests were returning 502 error. This was caused due my nginx server, which I was using as proxy. I had to increase proxy buffers, to be able to receive response from the server.

```
server {
  ...
  proxy_buffers   4 32k;
  proxy_buffer_size   32k;
}
```

Setting `large_client_header_buffers 4 16k` might also help.
Mainly the issue is that Sentry API requests events data, and IDs of events are all packed in URL, so when you have 50 events, it becomes quite big, and at least in my situation, my nginx proxy, which was relaying to docker sentry installation, had issue with processing such long URLs

Hope this helps

**Comment by BYK** [comment]
Hi @lorado thanks a lot for sharing your insights! If this keep happening we may add these to https://develop.sentry.dev/self-hosted/ for future reference under the troubleshooting section. If you want to give it a shot before that, I'd be more than happy to review it!

For now, I'm closing the issue as the original author doesn't seem to be responding for a long time.

**Comment by lorado** [comment]
Hey @BYK 
I don't know exact numbers required for buffer, but it definitely solves the problem. I just increased to some values I took on the internet, so in case you know more about required buffer size, feel free to adjust it.
I'd say you can add it to the Troubleshooting section and title something like "Proxy server settings" or mb directly "Nginx proxy settings", its up to you =)
