### ISSUE TITLE
500 Server Error after Setting up Sentry Self-Hosted

### ISSUE THREAD

**Issue by askar-ali** [getsentry/self-hosted#3456]
### Self-Hosted Version

24.10.0

### CPU Architecture

x86_64

### Docker Version

27.3.1, build ce12230

### Docker Compose Version

v2.29.7

### Machine Specification

- [x] My system meets the minimum system requirements of Sentry

### Steps to Reproduce

1. follow the official self-hosted installation guide.
2. Complete the setup and verify the Sentry instance is running properly.
3. Wait a few hours (or try to access specific endpoints, such as /api/0/relays/projectconfigs/).
4. Encounter a 500 Server Error.
5. This only happend after few many hours till that it working fine

### Expected Result

![Image](https://github.com/user-attachments/assets/3438b55c-f906-4e50-a9d7-ec7464560f3b)

### Actual Result

![Image](https://github.com/user-attachments/assets/ff29ed48-54ed-4f6a-843d-f75c670c57c3)

**Comment by TokiSeven** [comment]
i noticed - kafka is broken, from my side i'm sending a lot of traces from around 20 services

[2024-12-05 23:11:47,511] ERROR [QuorumController id=1001] processExpiredBrokerHeartbeat: controller event queue overloaded. Timed out heartbeat from broker 1001. (org.apache.kafka.controller.ReplicationControlManager)

also redis is overloaded (90gb ram) and can't work normally (i got errors even on command to flush db)

(error) MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

also interesting thing is - sentry went up after ~12 hours of downtime, but it doesn't proceed new traces or errors

**Comment by aldy505** [comment]
@askar-ali Hello, can you provide debug log of your Docker Compose project? Running `sudo docker compose logs --since 3h -t` and putting it on a Pastebin would help.

> i noticed - kafka is broken, from my side i'm sending a lot of traces from around 20 services
> 
> [2024-12-05 23:11:47,511] ERROR [QuorumController id=1001] processExpiredBrokerHeartbeat: controller event queue overloaded. Timed out heartbeat from broker 1001. (org.apache.kafka.controller.ReplicationControlManager)
> 
> also redis is overloaded (90gb ram) and can't work normally (i got errors even on command to flush db)
> 
> (error) MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
> 
> also interesting thing is - sentry went up after ~12 hours of downtime, but it doesn't proceed new traces or errors

@TokiSeven It seems you have a totally different issue. You might want to open a new issue for that.

**Comment by askar-ali** [comment]
The error occurred earlier because the PostgreSQL database was being exported at that time. When PostgreSQL was not being exported, the error did not occur.
